---

- name: "Setup Kubectl Environment"
  hosts: localhost
  run_once: true
  tasks:

    - name: "Get EKS Cluster region"
      command: "terraform output -raw region"
      register: region

    - name: "Get EKS cluster name"
      command: "terraform output -raw cluster_name"
      register: cluster_name

    - name: "Set kubernetes environment"
      command: "aws eks --region {{ region.stdout }} update-kubeconfig --name {{  cluster_name.stdout }}"
    

        