---

- name: Setup working namespace
  hosts: localhost
  tasks:
    - name: Create testing Kubernetes namespace
      community.kubernetes.k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present