---

- name: Deploy frontend apps
  hosts: localhost
  tasks:
    - name: Fetch kibana deployment status
      set_fact:
        deployments: "{{ lookup('community.kubernetes.k8s', kind='Deployment', namespace='testing', resource_name='kibana') }}"

    - name: Fetch kibana deployment status
      set_fact:
        service: "{{ lookup('community.kubernetes.k8s', kind='Service', namespace='testing', resource_name='kibana-svc') }}"
    
    - name: Delete kibana deployment if it exists
      community.kubernetes.k8s:
        namespace: testing
        state: absent
        kind: Deployment
        name: kibana
      when: deployments.status.availableReplicas >=1 or deployments.status.readyReplicas >= 1
      ignore_errors: yes
      
    - name: Delete kibana service if it exists
      community.kubernetes.k8s:
        namespace: testing
        state: absent
        kind: Deployment
        name: kibana
      when: service | length > 0
      ignore_errors: yes

    - name: Deploy kibana deployment
      community.kubernetes.k8s:
        namespace: testing
        state: present
        src: ./kibana/kibana_dep.yml

    - name: Deploy kibana service
      community.kubernetes.k8s:
        namespace: testing
        state: present
        src: ./kibana/kibana_svc.yml

    - name: Deploy counter pod
      community.kubernetes.k8s:
        namespace: testing
        state: present
        src: ./test_counter/counter_po.yml